### ISSUE TITLE
Standard compliancy

### ISSUE THREAD

**Issue by gioblu** [Girgitt/PJON-python#1]
Ciao @Girgitt its a pleasure to see the first python PJON implementation :)
I would be happy to help you to keep this implementation Standard compliant to let the users have a nice experience using these tools together. We are working on version 5 that will have some key differences compared to 4. Is there a chance to have a synchronous chat somewhere? Have you ever used gitter?

**Comment by Girgitt** [comment]
Hi @gioblu, It's a good idea to establish communication ensuring compliance with the future versions of your library. 

I have not used gitter, only slack, but please invite me to the community (if this is how gitter works). 

Eventually I will create CI tasks for PJON-python including functional tests with hardware (Arduino Uno and Nano for now) making it possible to validate each PJON branch automatically.

**Comment by gioblu** [comment]
Ciao @Girgitt, write me your email and I will invite you

**Comment by Girgitt** [comment]
Closing as compliance in the long run is ensured by switching PJON-python from a pure python implementation to a wrapper for PJON-piper which is a C++ client compiled from PJON sources.
